### ISSUE TITLE
[Linux] Could not build wheels for wxPython

### ISSUE THREAD

**Issue by arthurka-o** [Pasu4/neuro-api-tony#1]
Hello. Trying to install requirements gives me an error. Installing it in virtual env.
Fedora latest, Python 3.11.9 

[log.log](https://github.com/user-attachments/files/18221933/log.log)

I have those packages installed:
```
❯ dnf list installed "gtk3*"
Installed Packages              
gtk3.i686                          3.24.43-1.fc40                  @fedora-updates
gtk3.x86_64                        3.24.43-1.fc40                  @fedora-updates
gtk3-devel.x86_64                  3.24.43-1.fc40                  @updates
```

**Comment by Pasu4** [comment]
I have tested this with a fresh installation of Fedora 41 with Python 3.13.1 and it works for me after running `sudo dnf install g++ gtk3-devel python-config`.

If this solves the problem, please report back so I can close the issue and add it to the installation instructions.

```
$ dnf list installed "gtk3*"
Updating and loading repositories:
Repositories loaded.
Installed packages
gtk3.x86_64              3.24.43-2.fc41 anaconda
gtk3-devel.x86_64        3.24.43-2.fc41 fedora

Available packages
gtk3.i686                3.24.43-2.fc41 fedora
gtk3-devel.i686          3.24.43-2.fc41 fedora
gtk3-devel-docs.x86_64   3.24.43-2.fc41 fedora
gtk3-immodule-xim.x86_64 3.24.43-2.fc41 fedora
gtk3-immodules.x86_64    3.24.43-2.fc41 fedora
gtk3-tests.x86_64        3.24.43-2.fc41 fedora
```

**Comment by Pasu4** [comment]
Closing this for now, please reopen if this is not fixed.

**Comment by arthurka-o** [comment]
Hello :wave: 
Sorry for disappearing, just got time to test this again.
Want to preface that I misguided you a little (tehepero). I have Nobara 40 which is a fork of Fedora 40 (so not the latest).

I get the program running after back-and-forth with Claude. In my case, there was a problem that `pkg-config` couldn't find the GTK and xproto in the path because `PKG_CONFIG_PATH` was empty :shrug: 
```sh
export PKG_CONFIG_PATH="/usr/share/pkgconfig:/usr/lib64/pkgconfig:$PKG_CONFIG_PATH"
```
Also I had to install clang
```sh
sudo dnf install clang clang-devel
```

And now the app builds and launches, hooray :tada: 
Except that it crashes when it receives the message from Godot :joy: 
```
❯ python -m src

(__main__.py:538285): Gtk-WARNING **: 17:27:06.125: Invalid text buffer iterator: either the iterator is uninitialized, or the characters/pixbufs/widgets in the buffer have been modified since the iterator was created.
You must use marks, character numbers, or line numbers to preserve a position across buffer modifications.
You can apply tags and insert marks without invalidating your iterators,
but any mutation that affects 'indexable' buffer contents (contents that can be referred to by character offset)
will invalidate all outstanding iterators
[1]    538285 segmentation fault (core dumped)  python -m src
```
but it's probably for another issue
